POST https://localhost:56966/users/
Content-Type: application/json

{
    "name": "Joan Comas",
    "address": "Awesome street 7, Nicetown, Amazingland"
}

###
POST  https://va3rmrikf1.execute-api.us-west-1.amazonaws.com/Prod/users/
Content-Type: application/json

{
    "name": "Joan Comas",
    "address": "Awesome street 7, Nicetown, Amazingland"
}