###
DELETE https://n8vczqjr73.execute-api.eu-central-1.amazonaws.com/dev

""

###
GET https://n8vczqjr73.execute-api.eu-central-1.amazonaws.com/dev

""

###
HEAD https://n8vczqjr73.execute-api.eu-central-1.amazonaws.com/dev

###
OPTIONS https://n8vczqjr73.execute-api.eu-central-1.amazonaws.com/dev

""

###
PATCH https://n8vczqjr73.execute-api.eu-central-1.amazonaws.com/dev

""

###
POST https://n8vczqjr73.execute-api.eu-central-1.amazonaws.com/dev

""

###
PUT https://n8vczqjr73.execute-api.eu-central-1.amazonaws.com/dev

""